### ISSUE TITLE
Averages seem off

### ISSUE THREAD

**Issue by khrome83** [littletof/prettyBenching#4] opened 2020-06-17 12:39 UTC
I love the output. Really really nice work! I can't wait to see where this project goes. 

I am trying to make sense of the numbers, and I feel the averages are off. 

Take a lot of the screenshot below. This was run with --allow-hrtime.

<img width="676" alt="Screen Shot 2020-06-17 at 7 25 44 AM" src="https://user-images.githubusercontent.com/1844739/84897975-1e540200-b06c-11ea-90fe-92ea9b446415.png">

A few things to notice. 

1. The total time shows ~8 seconds. This does seem correct from the totally scientific method of counting "# Mississippi".  =)
2. The average time show 0.0496 ms. If you multiple this by 10,000 you should get something close to the 8 seconds. And you do. 
3. The individual runs are fairly stable, with 9984 taking 0.2065ms. If you multiple this by 9984 you should get something close to 8 seconds in milliseconds. Instead, you show something closer to 34 seconds. 

So I feel like the individual runs can't be trusted. This feels less of a formatting problem. If it was supposed to be `0.02065` the average time should have matched given than 99.8% of the runs took the same time.

Sorry, I don't have the code in GitHub to reproduce. But the output seems to be off pretty consistently. I figured I am either missing what the bars are representing or something else is wrong. 

Thanks!

**Comment by littletof** [comment] 2020-06-18 11:58
@khrome83 Thanks for your detailed feedback, I'm glad you like this project! 🙂

In versions before v0.1.0 the graphs were off for sure. I **hope** its fixed in v0.1.0.
Can you please try to run this with the new version, and see if it seems correct with that? The grouping of the results were off and it always had only one item in the first group.

(`precision` was moved into `parts` option )
(In the new version you can add extra metrics too, see if they help anything: https://github.com/littletof/prettyBenching#parts)

Knowing that the graph was bad, maybe the picture doesnt show the run you described, because I cant see, where the 8 seconds come from. (Maybe the scientific method wasn't calibrated? 😄)

On what the bars are representing: they visualise, how many results are in the timeframe from the time in its line, to the time in the next line. (or at least from v0.1.0 it should be the case).

If 0.1.0 doesn't solve this, I will try to find what the problem is.

**Comment by khrome83** [comment] 2020-06-18 12:38
<img width="667" alt="Screen Shot 2020-06-18 at 7 33 50 AM" src="https://user-images.githubusercontent.com/1844739/85020607-33956300-b136-11ea-9868-c0a34676a04b.png">

Does not seem like the graph represents the average correctly still. Directionally it is closer.

I also realized that I was wrong above. The total time is in milliseconds, right? It did take closer to 8 seconds but is reporting about a half-second to run.

**Comment by littletof** [comment] 2020-06-18 13:02
Yes, its in milliseconds.
The average time, and total time comes from deno itself, so its a given value. Deno only measures, and sums the times, that elapsed between `b.start()` and `b.stop()`, so if there are things outside these, it may cause extra times, not reported in total time. Maybe that's your case?

The graphs seem ok to me: `99.9%` of the valuesin the `ComplexParse` are between `0.0300ms` and `0.2776ms`. `Average` and `median` is in that range. This seems true for `Complex Serializer` too for me.

Maybe the visualisation is not clear enough? I'm planning to add an option to cut outlayers from the graph, which could help too. Any thoughts on that?

I will fiddle with it later today and see if I see any problems with the graph.

**Comment by khrome83** [comment] 2020-06-18 13:03
ok, so it's a "bucket" that it is fitting in, so its betwen 0.0300ms -> 0.2775ms?

I think that was my lack of understanding. Makes sense.

**Comment by littletof** [comment] 2020-06-18 13:06
Yes, I tried to represent it a bit better, but couldn't come up with a better solution other than the `_` before the group. I will try to figure out a better way to represent it. Or do you have an idea to fix it?
Anyhow, I will update the readme to make it more clear.

Is this issue resolved for you with the buckets thing? Are the values correct like this?

**Comment by khrome83** [comment] 2020-06-18 13:11
yeah. The `_` does not help me, not sure what it's referring too? Math notation I am not familar with?

But yeah, it does make sense. Thank you for the patients.

**Comment by littletof** [comment] 2020-06-18 13:21
I thought it would help indicate, that the group belongs to the range from this lines value, to the next lines value. But then it clearly doesnt help with that :D Will think of something.

Thanks for the feedback! This will be closed with #6.

**Comment by khrome83** [comment] 2020-06-18 13:34
sounds good. #6 looks good to me.

**Comment by littletof** [comment] 2020-06-18 13:43
Thanks! 0.1.1 will be out in a sec.

**Closed as completed by littletof** 2020-06-18 13:43 UTC
Labels: prettyBenchmarkResults
